### PR TITLE
Fix db issue

### LINKED ISSUE #1: Database fail on fresh start
Ran `cargo build --release` on a Windows 10 machine, I guess the database needs some migrations in order to be prepared:

```
$ .\target\release\rust-sudoku.exe
WGL: failed to create 3.2 context, trying 2.1
GL_VERSION: 4.6.0 Compatibility Profile Context 24.3.1.240216
thread 'main' panicked at src\save_win.rs:5:72:
called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: save"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by Pierstoval**
Fixes #1 
* Migrate db with have the main table, allows starting the project
* Make sure db is read and not recreated everytime, this allows keeping save games.

### CODE REVIEW

File: src/save_win.rs [hunk 1]
```diff
@@ -16,10 +16,37 @@ pub fn load(key: &str) -> Option<String> {
...
         "REPLACE INTO save (key, value) VALUES (?1, ?2)",
         params![key, value],
     )
     .unwrap();
 }
+
+fn migrate_db(db: &Connection) {
+    let mut stmt = db.prepare("CREATE TABLE IF NOT EXISTS save (key VARCHAR(255) PRIMARY KEY, value LONGTEXT);").unwrap();
+    stmt.execute(params![]).unwrap();
+}
```
Comment (Pierstoval) [inline src/save_win.rs:30]: There's also the `rusqlite_migration` crate that perfectly does the trick with proper SQL-files migrations, but I didn't want to complexify everything right now, the project is perfectly fine as-is :)

**Review by olafurw — APPROVED** [review]
